"""users table updated

Revision ID: 02232b35f4cd
Revises: 292058d84f6c
Create Date: 2018-11-11 00:07:43.000106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02232b35f4cd'
down_revision = '292058d84f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fname', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('lname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lname')
    op.drop_column('user', 'fname')
    # ### end Alembic commands ###
