"""files table updated

Revision ID: 5ccb612c7f12
Revises: 5f4200d51a8c
Create Date: 2018-11-08 17:07:46.878152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccb612c7f12'
down_revision = '5f4200d51a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'data')
    # ### end Alembic commands ###
