"""files table updated

Revision ID: 883e6c2662e1
Revises: ec0358cab779
Create Date: 2018-11-10 14:53:53.844185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883e6c2662e1'
down_revision = 'ec0358cab779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('viewers', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'viewers')
    # ### end Alembic commands ###
